---
title: "Lab 00 - Hello IDS!"
author: "Pang-Qiyu"
date: "`r Sys.Date()`"
output: html_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```

### Exercises 16-17

We set up the data frame. Edit the data below to include information about your team members.

```{r setup-tibble}
team_data <- tibble(
  name = c("Pang-Qiyu", "Ming", "Jason Xu", 
           "Vita","Joe"),
  github_username = c("Pang-Qiyu", "Ming-Sun-2007", "hanxindianbing0420", 
                      "e13365132-pixel", "lntani"), 
  colour = c("red", "green1", "blue", 
             "yellow", "pink"),
  hobby = c("reading", "reading", "reading", 
            "reading", "data science"),
  favourite_number = c(7, 8, 9, 10,7 )
  )

team_data
```

### Exercise 18

We now work on visualising our data. 

```{r bar-plot}
p1 <- ggplot(data = team_data, 
             mapping = aes(x = github_username, 
                           y = favourite_number,
                           fill = colour), 
             ) +
   geom_col() +
   scale_fill_identity()
p1
```

*Remove this text (including the stars), and add your answer for Exercise 18 here.*

